spring.application.name=character-api
  
spring.datasource.url=jdbc:h2:mem:testdb


spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url = postgresql://neondb_owner:npg_JmFRLT89fYqg@ep-proud-star-ahngsmmx-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

server.port=8082